### ISSUE TITLE
[M-4] CI Enhancements: macOS ARM64, Windows ARM64, fuzzing

### ISSUE THREAD

**Issue by crlotwhite** [crlotwhite/rune-caster#8]
## 🎯 목표
CI 매트릭스 확장 (macOS ARM64, Windows ARM64) 및 퍼징 테스트 통합으로 견고성과 커버리지 향상

### 새로운 플랫폼
- **macOS ARM64**: Apple Silicon 네이티브 빌드
- **Windows ARM64**: ARM64 Windows 지원
- **Linux ARM64**: 서버 환경 호환성

### 기존 매트릭스 개선
```yaml
# .github/workflows/ci.yml
strategy:
  matrix:
    os: [ubuntu-latest, windows-latest, macos-latest, macos-14] # M1
    arch: [x64, arm64]
    compiler: [gcc, clang, msvc]
    build_type: [Debug, Release]
    exclude:
      - os: ubuntu-latest
        arch: arm64
        compiler: msvc
```

### libFuzzer 통합
```cpp
// fuzz_rune_sequence.cpp
extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    try {
        auto seq = RuneSequence::from_utf8(
            std::string(reinterpret_cast<const char*>(data), size)
        );
        // 다양한 연산 테스트
        seq.normalize().tokenize().filter();
    } catch (...) {
        // 예외는 허용되지만 크래시는 안됨
    }
    return 0;
}
```

### OSS-Fuzz 통합
- Google OSS-Fuzz 프로젝트 등록
- 지속적인 퍼징 테스트 실행
- 취약점 자동 리포팅

## 🔧 구현 계획
1. **ARM64 빌드**: 크로스 컴파일 환경 구성
2. **퍼징 타겟**: 핵심 API별 퍼저 작성
3. **CI 통합**: GitHub Actions 워크플로우 확장
4. **성능 모니터링**: 플랫폼별 벤치마크

## ✅ 완료 조건
- [ ] macOS ARM64 빌드 성공
- [ ] Windows ARM64 빌드 성공
- [ ] libFuzzer 타겟 5개 이상 작성
- [ ] OSS-Fuzz 프로젝트 등록
- [ ] CI 실행 시간 최적화 (< 30분)

**로드맵 ID**: M-4
